# Generated by Django 5.0.7 on 2024-09-13 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ageRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_rating', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='movies',
            name='age_rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agerating'),
        ),
    ]
