# Generated by Django 5.0.7 on 2024-09-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_agerating_alter_movies_age_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='poster/')),
                ('urlImage', models.CharField(max_length=255)),
            ],
        ),
    ]
