# Generated by Django 5.0.7 on 2024-09-20 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='urlImage',
        ),
    ]
